---
- name: Create stack root directory
  file:
    path: "{{ hg_server_container_stack_location }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create Pihole directories
  file:
    path: "{{ pihole_config_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Ensure DNS stub resolver is disabled
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener='
    line: DNSStubListener=no

- name: Copy Docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ hg_server_container_stack_location }}/docker-compose.yml"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Start Docker containers using docker-compose
  community.docker.docker_compose:
    project_src: "{{ hg_server_container_stack_location }}"
  tags: start-stacks

- name: Adding the Systemd units for docker-compose management
  import_role:
    name: docker-compose-systemd
  vars:
    docker_compose_dir_path: "{{ hg_server_container_stack_location }}"
    stack_name: container-stack-home-guardian

- name: Stop Docker containers if running
  block:
    - name: Check wether the docker file exist
      stat:
        path: "{{ hg_server_container_stack_location }}/docker-compose.yml"
      register: hg_server_container_stack_location_docker_compose_file

    - name: Check validity of compose file
      shell: "docker-compose -f {{ hg_server_container_stack_location }}/docker-compose.yml config"
      register: hg_server_container_stack_docker_compose_file_validate
      ignore_errors: yes

    - name: Stopping using docker compose
      community.docker.docker_compose:
        project_src: "{{ hg_server_container_stack_location }}"
        state: absent
      when: hg_server_container_stack_location_docker_compose_file.stat.exists and hg_server_container_stack_docker_compose_file_validate.failed|bool != true
  tags: [ 'never', 'stop-stacks' ]